# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.2.1
        with:
          architecture: 'x64'  # or: 'x64', 'x86', 'arm32', 'arm64' (or 'aarch64')
          distribution: 'full' # or: 'minimal'
          variant: 'CS'        # or: 'BC' for Racket Before Chez
          version: '8.0'       # or: 'stable' for the latest version, 'current' for the latest snapshot
      - name: Install package threading
        run: raco pkg install threading
      - name: Run tests with rackunit
        run: raco test space-invaders-test.rkt
